apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: golang-app-package.default.tap.20240212132214.0.0
spec:
  refName: golang-app-package.default.tap
  version: 20240212132214.0.0
  releaseNotes: |
    Release v20240212132214.0.0 of package golang-app-package.default.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd08293d220f3f0d9d55112edf.azurecr.io/tap-install/tcc-test/golang-app-package-bundle@sha256:ef1a993c9aad43653e899047c44d488f0e3a16738920549342fb59eefee101a0
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          description: Used to generate resource names.
          default: golang-app-package
        minScale:
          type: integer
          nullable: true
          description: If set, overrides the default Knative Service minimum number of replicas.
          default: null
        maxScale:
          type: integer
          nullable: true
          description: If set, overrides the default Knative Service maximum number of replicas.
          default: null
        livenessProbe:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].livenessProbe set by the Supply Chain.
          default: null
        readinessProbe:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].readinessProbe set by the Supply Chain.
          default: null
        resources:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].resources set by the Supply Chain.
          default: null
        env:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].env set by the Supply Chain.
          default: null
        securityContext:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].securityContext set by the Supply Chain.
          default: null
        knativeAnnotations:
          nullable: true
          description: Specifies additional annotations to merge into Knative Service.spec.metadata.annotations.
          default: null
