apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: golang-app-package.example.com-pkgi
spec:
  packageRef:
    refName: golang-app-package.example.com
    versionSelection:
      constraints: 20240206231146.0.0
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: golang-app-package-secret
