apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: steeltoe-app-package.default.tap.20240215033054.0.0
spec:
  refName: steeltoe-app-package.default.tap
  version: 20240215033054.0.0
  releaseNotes: |
    Release v20240215033054.0.0 of package steeltoe-app-package.default.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd2d6370deffc08536ff8b9b6d.azurecr.io/tap-install/tcc-test/steeltoe-app-package-bundle@sha256:8dff22ed00aaa07ef783395577e9cf95264302740ad916d29a1e04e1185cc7cd
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          description: Used to generate resource names.
          default: steeltoe-app-package
        minScale:
          type: string
          nullable: true
          description: If set, overrides the default Knative Service minimum number of replicas.
          default: null
        maxScale:
          type: string
          nullable: true
          description: If set, overrides the default Knative Service maximum number of replicas.
          default: null
        livenessProbe:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].livenessProbe set by the Supply Chain.
          default: null
        readinessProbe:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].readinessProbe set by the Supply Chain.
          default: null
        resources:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].resources set by the Supply Chain.
          default: null
        env:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].env set by the Supply Chain.
          default: null
        securityContext:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].securityContext set by the Supply Chain.
          default: null
        knativeAnnotations:
          nullable: true
          description: Specifies additional annotations to merge into Knative Service.spec.metadata.annotations.
          default: null
