apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: golang-app-kaniko-package.default.tap-pkgi
spec:
  packageRef:
    refName: golang-app-kaniko-package.default.tap
    versionSelection:
      constraints: 20240312225302.0.0
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: golang-app-kaniko-package.default.tap-values
