---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: run-ns
  name: app-package-and-pkgi-install-role
rules:
  - apiGroups: ["data.packaging.carvel.dev"]
    resources: ["packages"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: ["packaging.carvel.dev"]
    resources: ["packageinstalls"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: run-ns
  name: app-cr-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "services"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-package-and-pkgi-install-rolebinding
  namespace: run-ns
subjects:
- kind: ServiceAccount
  name: default
  namespace: run-ns
roleRef:
  kind: Role
  name: app-package-and-pkgi-install-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-cr-rolebinding
  namespace: run-ns
subjects:
- kind: ServiceAccount
  name: default
  namespace: run-ns
roleRef:
  kind: Role
  name: app-cr-role
  apiGroup: rbac.authorization.k8s.io
---
