apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: maven-app-package.example.com.20240206155623.0.0
spec:
  refName: maven-app-package.example.com
  version: 20240206155623.0.0
  releaseNotes: |
    Release v20240206155623.0.0 of package maven-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd51c4dbd22cf69b5905d65044.azurecr.io/tap-install/tcc-test/maven-app-package-bundle@sha256:bce2f41687d18a9f21fa9f8890d59a0c31eb29db9e6914045b82cfa97afb28e3
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
