apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: maven-app-package.example.com.20240201101242.0.0
spec:
  refName: maven-app-package.example.com
  version: 20240201101242.0.0
  releaseNotes: |
    Release v20240201101242.0.0 of package maven-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherdc712323c8cf9bfafa6bc7f5c.azurecr.io/tap-install/tcc-test/maven-app-package-bundle@sha256:dadcfe7359c2b18bdc30d4c43c475e3a6ab3086e642fe98c2347d889fca2adb0
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
