apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: maven-app-package.example.com.20240131213451.0.0
spec:
  refName: maven-app-package.example.com
  version: 20240131213451.0.0
  releaseNotes: |
    Release v20240131213451.0.0 of package maven-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherdf78a0cd6895430557e074e58.azurecr.io/tap-install/tcc-test/maven-app-package-bundle@sha256:0f746775060cacb67230f06499af04ccd99ea382501e1bb0fe9203c877deaaaf
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
