apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: maven-app-package.example.com.20240201193419.0.0
spec:
  refName: maven-app-package.example.com
  version: 20240201193419.0.0
  releaseNotes: |
    Release v20240201193419.0.0 of package maven-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherdfbffeff5cab8cb7c0fcaf560.azurecr.io/tap-install/tcc-test/maven-app-package-bundle@sha256:160478f4963c09c90dd5ba7184a653af33e7af0a30fa2d115887a5ead594a1dc
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
