apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: maven-app-package.example.com.20240206221309.0.0
spec:
  refName: maven-app-package.example.com
  version: 20240206221309.0.0
  releaseNotes: |
    Release v20240206221309.0.0 of package maven-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd462ba26f46a1868684e3fcca.azurecr.io/tap-install/tcc-test/maven-app-package-bundle@sha256:53b99cef9efced1cf552bda9616856355cad9821d5b8688a93b3d42eb00bba12
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
