apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: maven-app-package.example.com.20240207043112.0.0
spec:
  refName: maven-app-package.example.com
  version: 20240207043112.0.0
  releaseNotes: |
    Release v20240207043112.0.0 of package maven-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd462ba26f46a1868684e3fcca.azurecr.io/tap-install/tcc-test/maven-app-package-bundle@sha256:3c1ab66f5245a97a5442c394cda2ece3f03cc262f760ac9786a0ef6484e5ad8d
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
