apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: maven-app-package.example.com.20240206021409.0.0
spec:
  refName: maven-app-package.example.com
  version: 20240206021409.0.0
  releaseNotes: |
    Release v20240206021409.0.0 of package maven-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd5f606f921541307a9c8bf14e.azurecr.io/tap-install/tcc-test/maven-app-package-bundle@sha256:92c2ae5b68dd5b1ae2487eab38a9717d1cc0056345741ddbc4ac331b2a2ed9cd
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
