apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: maven-app-package.example.com.20240206232853.0.0
spec:
  refName: maven-app-package.example.com
  version: 20240206232853.0.0
  releaseNotes: |
    Release v20240206232853.0.0 of package maven-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd462ba26f46a1868684e3fcca.azurecr.io/tap-install/tcc-test/maven-app-package-bundle@sha256:3cad5734cdfef24219692be1fb13c4fd70b1f1e445ecbc236a8ac1f2757a6ffd
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
