apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-maven-kaniko
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/component: run
    carto.run/workload-name: app-maven-kaniko
spec:
  template:
    containers:
    - image: gcr.io/ship-interfaces-dev/app-maven-kaniko@sha256:53c7670981b5022de898564c03fd4d3b8c6181613de299eb51e90b1f51c88d45
      name: workload
      resources: {}
      securityContext:
        runAsUser: 1000
    serviceAccountName: default
