apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-maven-kaniko-subpath
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/component: run
    carto.run/workload-name: app-maven-kaniko-subpath
spec:
  template:
    containers:
    - image: gcr.io/ship-interfaces-dev/app-maven-kaniko-subpath@sha256:206fefe1b01b099616fd75c9ce9c48c1164c0a0816d7f4f043decda5eadc9057
      name: workload
      resources: {}
      securityContext:
        runAsUser: 1000
    serviceAccountName: default
