apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-golang-kaniko-chainguard
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/component: run
    carto.run/workload-name: app-golang-kaniko-chainguard
spec:
  template:
    containers:
    - image: gcr.io/ship-interfaces-dev/app-golang-kaniko-chainguard@sha256:f603e1cdbe9b52d51d69ab63e4ad1086cc309691241fe13ec81c9298dcc1f4b4
      name: workload
      resources: {}
      securityContext:
        runAsUser: 1000
    serviceAccountName: default
