apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: maven-app-package.default.tap.20240209145232.0.0
spec:
  refName: maven-app-package.default.tap
  version: 20240209145232.0.0
  releaseNotes: |
    Release v20240209145232.0.0 of package maven-app-package.default.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherdc87b31ca0fc1f4d622ab8d21.azurecr.io/tap-install/tcc-test/maven-app-package-bundle@sha256:c5e080c1f534035923f56f3611d5e569cdd18dacd793bc444500c5d89634962f
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          description: Used to generate resource names.
          default: maven-app-package
        minScale:
          type: integer
          nullable: true
          description: If set, overrides the default Knative Service minimum number of replicas.
          default: null
        maxScale:
          type: integer
          nullable: true
          description: If set, overrides the default Knative Service maximum number of replicas.
          default: null
        livenessProbe:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].livenessProbe set by the Supply Chain.
          default: null
        readinessProbe:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].readinessProbe set by the Supply Chain.
          default: null
        resources:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].resources set by the Supply Chain.
          default: null
        env:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].env set by the Supply Chain.
          default: null
        securityContext:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].securityContext set by the Supply Chain.
          default: null
        knativeAnnotations:
          nullable: true
          description: Specifies additional annotations to merge into Knative Service.spec.metadata.annotations.
          default: null
