apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: maven-app-package.default.tap.20240223180342.0.0
spec:
  refName: maven-app-package.default.tap
  version: 20240223180342.0.0
  releaseNotes: |
    Release v20240223180342.0.0 of package maven-app-package.default.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd98f7f74b66d65c8ebca023e2.azurecr.io/tap-install/tcc-test/maven-app-package-bundle@sha256:c0bbdf39cd13009c03db948a96ac2d93f3851db2513caa742aed7bafecd4c9bd
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          description: Used to generate resource names.
          default: maven-app-package
        minScale:
          type: string
          nullable: true
          description: If set, overrides the default Knative Service minimum number of replicas.
          default: null
        maxScale:
          type: string
          nullable: true
          description: If set, overrides the default Knative Service maximum number of replicas.
          default: null
        livenessProbe:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].livenessProbe set by the Supply Chain.
          default: null
        readinessProbe:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].readinessProbe set by the Supply Chain.
          default: null
        resources:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].resources set by the Supply Chain.
          default: null
        env:
          type: array
          description: Merges with the default Deployment.spec.containers[0].env set by the Supply Chain. If there is a conflict, the value set here will be used.
          items:
            type: object
            additionalProperties: false
            properties:
              name:
                type: string
                default: ""
              value:
                type: string
                default: ""
          default: []
        securityContext:
          nullable: true
          description: Overrides the default Knative Service.spec.containers[0].securityContext set by the Supply Chain.
          default: null
        knativeAnnotations:
          nullable: true
          description: Specifies additional annotations to merge into Knative Service.spec.metadata.annotations.
          default: null
