apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-golang-kaniko-cg
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/component: run
    carto.run/workload-name: app-golang-kaniko-cg
spec:
  template:
    containers:
    - image: gcr.io/ship-interfaces-dev/app-golang-kaniko-cg@sha256:7f67e0a3faba61969c44c219ec293ee4ae19bdaa05b7ff7707609d1aafc17988
      name: workload
      resources: {}
      securityContext:
        runAsUser: 1000
    serviceAccountName: default
