apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: mypackage.example.com.20231005105519.0.0
spec:
  refName: mypackage.example.com
  version: 20231005105519.0.0
  releaseNotes: |
    Release v20231005105519.0.0 of package mypackage.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/ship-interfaces-dev/example/example-bundle@sha256:34517b60e2f92503e45acc7e8791c5ba06ca3e52fa0666cd72ead86d4318b6d7
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}
