apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: mypackage.example.com.20231005160431.0.0
spec:
  refName: mypackage.example.com
  version: 20231005160431.0.0
  releaseNotes: |
    Release v20231005160431.0.0 of package mypackage.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/ship-interfaces-dev/example/example-bundle@sha256:6881ccad22e319e6bcf79b27de974acd5c945380292257c78d9a63198594e8cf
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}
