apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: app-maven-kpack.example.com.20231130100711.0.0
spec:
  refName: app-maven-kpack.example.com
  version: 20231130100711.0.0
  releaseNotes: |
    Release v20231130100711.0.0 of package app-maven-kpack.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/ship-interfaces-dev/app-maven-kpack/app-maven-kpack-bundle@sha256:48858efec4bc106b7d9894059dde2f77105ebfff998f70f22063c5f24e2e1b65
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}
