apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: golang-app.example.com-pkgi
spec:
  packageRef:
    refName: golang-app.example.com
    versionSelection:
      constraints: 20240129151835.0.0
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: golang-app-secret
