apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-golang-kaniko
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/component: run
    carto.run/workload-name: app-golang-kaniko
spec:
  template:
    containers:
    - image: gcr.io/ship-interfaces-dev/app-golang-kaniko@sha256:fff6ea2ca3dede17cc90ef6b8e7ce84930b13f4a3a679e18877012ccc2b9a25a
      name: workload
      resources: {}
      securityContext:
        runAsUser: 1000
    serviceAccountName: default
