apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-golang-kaniko
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/component: run
    carto.run/workload-name: app-golang-kaniko
spec:
  template:
    containers:
    - image: gcr.io/ship-interfaces-dev/app-golang-kaniko@sha256:59196f52a494a8574006de7d16ad8b1a2103a77268bdd1149dc6e457430bd447
      name: workload
      resources: {}
      securityContext:
        runAsUser: 1000
    serviceAccountName: default
