apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: steeltoe-app-package.example.com.20240202192509.0.0
spec:
  refName: steeltoe-app-package.example.com
  version: 20240202192509.0.0
  releaseNotes: |
    Release v20240202192509.0.0 of package steeltoe-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd21c317969d4205b2fdcc8877.azurecr.io/tap-install/tcc-test/steeltoe-app-package-bundle@sha256:5112cfa22f849c9a23b27ff70d9a9caffdd0e498d8326fb3aef3669983c86a07
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
