apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: steeltoe-app-package.example.com.20240207165451.0.0
spec:
  refName: steeltoe-app-package.example.com
  version: 20240207165451.0.0
  releaseNotes: |
    Release v20240207165451.0.0 of package steeltoe-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd14320e91e2db7d54d3d73987.azurecr.io/tap-install/tcc-test/steeltoe-app-package-bundle@sha256:42e74b7c0cc1e98c7cf6bff7cf9e6809e7bd7fcc221f085674fc3b40ea4073a8
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
