apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: steeltoe-app-package.example.com.20240206235121.0.0
spec:
  refName: steeltoe-app-package.example.com
  version: 20240206235121.0.0
  releaseNotes: |
    Release v20240206235121.0.0 of package steeltoe-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd35e2f26c8745612b39902678.azurecr.io/tap-install/tcc-test/steeltoe-app-package-bundle@sha256:c4956e4c5fc5b134c7c472fcaa146ce50c899061484a64c347cb40deaca2f3fa
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
