apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: steeltoe-app-package.example.com.20240206120512.0.0
spec:
  refName: steeltoe-app-package.example.com
  version: 20240206120512.0.0
  releaseNotes: |
    Release v20240206120512.0.0 of package steeltoe-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherdbb64423e8b41325237483e1f.azurecr.io/tap-install/tcc-test/steeltoe-app-package-bundle@sha256:8997c564964e2d514a51820fb0616b4b02a822a77a9dd740336b238b3f92d21d
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
