apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: steeltoe-app-package.example.com.20240206195451.0.0
spec:
  refName: steeltoe-app-package.example.com
  version: 20240206195451.0.0
  releaseNotes: |
    Release v20240206195451.0.0 of package steeltoe-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd462ba26f46a1868684e3fcca.azurecr.io/tap-install/tcc-test/steeltoe-app-package-bundle@sha256:1d3eb120232e02029a90b7bfa4ea0113b4c24e7571bd98927b881df426056f60
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
