apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: steeltoe-app-package.example.com.20240207101455.0.0
spec:
  refName: steeltoe-app-package.example.com
  version: 20240207101455.0.0
  releaseNotes: |
    Release v20240207101455.0.0 of package steeltoe-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd8a03132a30a4d8c996af24c8.azurecr.io/tap-install/tcc-test/steeltoe-app-package-bundle@sha256:ef5e203bf0d3a025943f1a7030998a24ae5825e68f77838f7928f42cee2ff0f0
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
