apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-golang-kaniko-sp
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/component: run
    carto.run/workload-name: app-golang-kaniko-sp
spec:
  template:
    containers:
    - image: gcr.io/ship-interfaces-dev/app-golang-kaniko-sp@sha256:480097385c83655e4c888189ba19a7570062057227cf1b8b2f168c85bc114cfa
      name: workload
      resources: {}
      securityContext:
        runAsUser: 1000
    serviceAccountName: default
