apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: app-maven-kpack-fails-at-image-build.example.com.20231130100810.0.0
spec:
  refName: app-maven-kpack-fails-at-image-build.example.com
  version: 20231130100810.0.0
  releaseNotes: |
    Release v20231130100810.0.0 of package app-maven-kpack-fails-at-image-build.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/ship-interfaces-dev/app-maven-kpack-fails-at-image-build/app-maven-kpack-fails-at-image-build-bundle@sha256:9d1215dd9e41bfc3e63849747ebc73447d6c234a16d8dc9ac0ed2a8a86b2ad75
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}
