apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.garethjevans.org.20230823221146.0.0
spec:
  refName: where-for-dinner-search.garethjevans.org
  version: 20230823221146.0.0
  releaseNotes: |
    Release v20230823221146.0.0 of package where-for-dinner-search.garethjevans.org
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/ship-interfaces-dev/where-for-dinner-search-bundle@sha256:34517b60e2f92503e45acc7e8791c5ba06ca3e52fa0666cd72ead86d4318b6d7
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}
