apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: golang-app-package.example.com.20240206203130.0.0
spec:
  refName: golang-app-package.example.com
  version: 20240206203130.0.0
  releaseNotes: |
    Release v20240206203130.0.0 of package golang-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherdb02122f3170a1a6ac1ef4fcc.azurecr.io/tap-install/tcc-test/golang-app-package-bundle@sha256:9b428c9c48e568bd5857ab51e4f681e3c2135a55f6affdd6d27408d067c5a01a
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
