apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: golang-app-package.example.com.20240207015348.0.0
spec:
  refName: golang-app-package.example.com
  version: 20240207015348.0.0
  releaseNotes: |
    Release v20240207015348.0.0 of package golang-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd960400e0c49845abae6f4c3f.azurecr.io/tap-install/tcc-test/golang-app-package-bundle@sha256:203cbdca0dce01219ec655d1cffe9ae7ee0508b32dc3e7c7543d10c73521d7a6
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
