apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: golang-app-package.example.com.20240131213348.0.0
spec:
  refName: golang-app-package.example.com
  version: 20240131213348.0.0
  releaseNotes: |
    Release v20240131213348.0.0 of package golang-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherdf78a0cd6895430557e074e58.azurecr.io/tap-install/tcc-test/golang-app-package-bundle@sha256:1d95eab3009565e6be1207109d16ae55825519a015446b73696ea370ded966e4
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
