apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: golang-app-package.example.com.20240207162559.0.0
spec:
  refName: golang-app-package.example.com
  version: 20240207162559.0.0
  releaseNotes: |
    Release v20240207162559.0.0 of package golang-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherdcf4f4d5daa58a3933cce7cc9.azurecr.io/tap-install/tcc-test/golang-app-package-bundle@sha256:6e7a33cd678de7621f5d1fbb5aa71ae28ebb538eb6e1fa29a959752bf1c3be6f
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
