apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: golang-app-package.example.com.20240206234802.0.0
spec:
  refName: golang-app-package.example.com
  version: 20240206234802.0.0
  releaseNotes: |
    Release v20240206234802.0.0 of package golang-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd35e2f26c8745612b39902678.azurecr.io/tap-install/tcc-test/golang-app-package-bundle@sha256:636f84df23a4a95595db8b22c04264ca46462bca8a2dbd510f16e72f0e1a82d3
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
