apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: golang-app-package.example.com.20240201195150.0.0
spec:
  refName: golang-app-package.example.com
  version: 20240201195150.0.0
  releaseNotes: |
    Release v20240201195150.0.0 of package golang-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd3bdd94083e04aebfb9a05089.azurecr.io/tap-install/tcc-test/golang-app-package-bundle@sha256:fe6c010d4b13df4acfbf4f02dda246db444cc859a09366d62211d5916cc06bf9
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
