apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: golang-app-package.example.com.20240201101405.0.0
spec:
  refName: golang-app-package.example.com
  version: 20240201101405.0.0
  releaseNotes: |
    Release v20240201101405.0.0 of package golang-app-package.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherdc712323c8cf9bfafa6bc7f5c.azurecr.io/tap-install/tcc-test/golang-app-package-bundle@sha256:01f94da195b5799d39dacedcf84282b8b49aab29f5068a19ac653f81b3302e18
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
