apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: golang-app-package.example.com.default.tap-pkgi
spec:
  packageRef:
    refName: golang-app-package.example.com.default.tap
    versionSelection:
      constraints: 20240207202246.0.0
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: golang-app-package-values
